<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class EntidadsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        Schema::disableForeignKeyConstraints();
        \DB::table('entidads')->delete();

        \DB::table('entidads')->insert(array (
            0 =>
            array (
                'id' => 1,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 144,
                'email' => 'notaria144@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 11:40:10',
                'updated_at' => '2024-05-17 11:40:10',
            ),
            1 =>
            array (
                'id' => 2,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 1,
                'email' => 'not1solorzano@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:07:23',
                'updated_at' => '2024-05-17 14:07:23',
            ),
            2 =>
            array (
                'id' => 3,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 2,
                'email' => 'gestorias@notaria2.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:08:23',
                'updated_at' => '2024-05-17 14:08:23',
            ),
            3 =>
            array (
                'id' => 4,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 3,
                'email' => 'edgar_frb2006@yahoo.com.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:08:53',
                'updated_at' => '2024-05-17 14:08:53',
            ),
            4 =>
            array (
                'id' => 5,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 4,
                'email' => 'np04.mich@outlook.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:10:26',
                'updated_at' => '2024-05-17 14:10:26',
            ),
            5 =>
            array (
                'id' => 6,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 5,
                'email' => 'notaria.5.mich@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:10:50',
                'updated_at' => '2024-05-17 14:10:50',
            ),
            6 =>
            array (
                'id' => 7,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 6,
                'email' => 'kaligaab@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:11:23',
                'updated_at' => '2024-05-17 14:11:23',
            ),
            7 =>
            array (
                'id' => 8,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 7,
                'email' => 'isr@notariasiete.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:11:53',
                'updated_at' => '2024-05-17 14:11:53',
            ),
            8 =>
            array (
                'id' => 9,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 8,
                'email' => 'notariaocholapiedad@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:12:21',
                'updated_at' => '2024-05-17 14:12:21',
            ),
            9 =>
            array (
                'id' => 10,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 9,
                'email' => 'notarionueve@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:12:44',
                'updated_at' => '2024-05-17 14:12:44',
            ),
            10 =>
            array (
                'id' => 11,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 10,
                'email' => 'notariadiez@outlook.es',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:13:22',
                'updated_at' => '2024-05-17 14:13:22',
            ),
            11 =>
            array (
                'id' => 12,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 11,
                'email' => 'luisloya@notariaoncemich.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:13:43',
                'updated_at' => '2024-05-17 14:13:43',
            ),
            12 =>
            array (
                'id' => 13,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 12,
                'email' => 'aina_not12@yahoo.com.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:14:00',
                'updated_at' => '2024-05-17 14:14:00',
            ),
            13 =>
            array (
                'id' => 14,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 13,
                'email' => 'notariaocegueda13@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:14:21',
                'updated_at' => '2024-05-17 14:14:21',
            ),
            14 =>
            array (
                'id' => 15,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 14,
                'email' => 'servinmaldonadopatricia@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:14:38',
                'updated_at' => '2024-05-17 14:14:38',
            ),
            15 =>
            array (
                'id' => 16,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 15,
                'email' => 'notariapub.15@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:14:57',
                'updated_at' => '2024-05-17 14:14:57',
            ),
            16 =>
            array (
                'id' => 17,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 16,
                'email' => 'notario16mich@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:15:32',
                'updated_at' => '2024-05-17 14:15:32',
            ),
            17 =>
            array (
                'id' => 18,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 17,
                'email' => 'notaria_17@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:15:54',
                'updated_at' => '2024-05-17 14:15:54',
            ),
            18 =>
            array (
                'id' => 19,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 19,
                'email' => 'eduardochcarreon@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => '2024-05-17 14:16:21',
                'updated_at' => '2024-05-17 14:16:30',
            ),
            19 =>
            array (
                'id' => 20,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 20,
                'email' => 'notaria20zinapecuaro@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:16:47',
                'updated_at' => '2024-05-17 14:16:47',
            ),
            20 =>
            array (
                'id' => 21,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 21,
                'email' => 'trasladosnotaria21@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:17:07',
                'updated_at' => '2024-05-17 14:17:07',
            ),
            21 =>
            array (
                'id' => 22,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 22,
                'email' => 'notaria22uruapan@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:17:28',
                'updated_at' => '2024-05-17 14:17:28',
            ),
            22 =>
            array (
                'id' => 23,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 23,
                'email' => 'notario23jm@prodigy.net.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:17:49',
                'updated_at' => '2024-05-17 14:17:49',
            ),
            23 =>
            array (
                'id' => 24,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 24,
                'email' => 'Yolandaea.notaria24@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:18:11',
                'updated_at' => '2024-05-17 14:18:11',
            ),
            24 =>
            array (
                'id' => 25,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 26,
                'email' => 'notaria_26@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:19:11',
                'updated_at' => '2024-05-17 14:19:11',
            ),
            25 =>
            array (
                'id' => 26,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 27,
                'email' => 'notariap27@outlook.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:19:31',
                'updated_at' => '2024-05-17 14:19:31',
            ),
            26 =>
            array (
                'id' => 27,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 28,
                'email' => 'vicentepineda28@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:19:48',
                'updated_at' => '2024-05-17 14:19:48',
            ),
            27 =>
            array (
                'id' => 28,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 29,
                'email' => 'notaria29upn@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:20:08',
                'updated_at' => '2024-05-17 14:20:08',
            ),
            28 =>
            array (
                'id' => 29,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 30,
                'email' => 'traslados@notaria30mlm.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:20:27',
                'updated_at' => '2024-05-17 14:20:27',
            ),
            29 =>
            array (
                'id' => 30,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 31,
                'email' => 'notaria31michoacan@outlook.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:20:45',
                'updated_at' => '2024-05-17 14:20:45',
            ),
            30 =>
            array (
                'id' => 31,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 32,
                'email' => 'notaria32@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:21:24',
                'updated_at' => '2024-05-17 14:21:24',
            ),
            31 =>
            array (
                'id' => 32,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 33,
                'email' => 'gestionnot33@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:21:47',
                'updated_at' => '2024-05-17 14:21:47',
            ),
            32 =>
            array (
                'id' => 33,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 34,
                'email' => 'notaria34morelia@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:22:12',
                'updated_at' => '2024-05-17 14:22:12',
            ),
            33 =>
            array (
                'id' => 34,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 35,
                'email' => 'lagunaslizy88@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:22:38',
                'updated_at' => '2024-05-17 14:22:38',
            ),
            34 =>
            array (
                'id' => 35,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 36,
                'email' => 'notaria_36_michoacan@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:22:53',
                'updated_at' => '2024-05-17 14:22:53',
            ),
            35 =>
            array (
                'id' => 36,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 37,
                'email' => 'not37zacapu@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:23:10',
                'updated_at' => '2024-05-17 14:23:10',
            ),
            36 =>
            array (
                'id' => 37,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 38,
                'email' => 'notario38@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:23:30',
                'updated_at' => '2024-05-17 14:23:30',
            ),
            37 =>
            array (
                'id' => 38,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 39,
                'email' => 'magabar39@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:23:53',
                'updated_at' => '2024-05-17 14:23:53',
            ),
            38 =>
            array (
                'id' => 39,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 40,
                'email' => 'not.40.ario@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:24:14',
                'updated_at' => '2024-05-17 14:24:14',
            ),
            39 =>
            array (
                'id' => 40,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 41,
                'email' => 'lanotaria_41@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:24:35',
                'updated_at' => '2024-05-17 14:24:35',
            ),
            40 =>
            array (
                'id' => 41,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 42,
                'email' => 'estradecus@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:24:51',
                'updated_at' => '2024-05-17 14:24:51',
            ),
            41 =>
            array (
                'id' => 42,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 43,
                'email' => 'licmoreno43@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:25:07',
                'updated_at' => '2024-05-17 14:25:07',
            ),
            42 =>
            array (
                'id' => 43,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 44,
                'email' => 'notario.publico@yahoo.com.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:25:24',
                'updated_at' => '2024-05-17 14:25:24',
            ),
            43 =>
            array (
                'id' => 44,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 45,
                'email' => 'notaria45catastro@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:25:36',
                'updated_at' => '2024-05-17 14:25:36',
            ),
            44 =>
            array (
                'id' => 45,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 46,
                'email' => 'navarro46notaria@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-17 14:26:02',
                'updated_at' => '2024-05-17 14:26:02',
            ),
            45 =>
            array (
                'id' => 46,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 48,
                'email' => 'notaria48eduardo@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 08:50:32',
                'updated_at' => '2024-05-20 08:50:32',
            ),
            46 =>
            array (
                'id' => 47,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 49,
                'email' => 'notaria_49@live.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 08:50:53',
                'updated_at' => '2024-05-20 08:50:53',
            ),
            47 =>
            array (
                'id' => 48,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 50,
                'email' => 'tramitesnotaria50mich@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 08:51:12',
                'updated_at' => '2024-05-20 08:51:12',
            ),
            48 =>
            array (
                'id' => 49,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 51,
                'email' => 'notaria51_1@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 08:51:28',
                'updated_at' => '2024-05-20 08:51:28',
            ),
            49 =>
            array (
                'id' => 50,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 52,
                'email' => 'tramitesenlinea@notaria52morelia.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 08:51:44',
                'updated_at' => '2024-05-20 08:51:44',
            ),
            50 =>
            array (
                'id' => 51,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 53,
                'email' => 'gestoria@notaria53michoacan.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => '2024-05-20 08:52:00',
                'updated_at' => '2024-05-20 08:52:09',
            ),
            51 =>
            array (
                'id' => 52,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 54,
                'email' => 'notariapublica54moreliamich@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 08:52:59',
                'updated_at' => '2024-05-20 08:52:59',
            ),
            52 =>
            array (
                'id' => 53,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 55,
                'email' => 'notaria55michoacan@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 08:53:18',
                'updated_at' => '2024-05-20 08:53:18',
            ),
            53 =>
            array (
                'id' => 54,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 56,
                'email' => 'notarianumero56@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 08:53:34',
                'updated_at' => '2024-05-20 08:53:34',
            ),
            54 =>
            array (
                'id' => 55,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 57,
                'email' => 'notario57zit@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 08:53:47',
                'updated_at' => '2024-05-20 08:53:47',
            ),
            55 =>
            array (
                'id' => 56,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 58,
                'email' => 'notariapublica_58@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 08:58:08',
                'updated_at' => '2024-05-20 08:58:08',
            ),
            56 =>
            array (
                'id' => 57,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 59,
                'email' => 'notaria59@prodigy.net.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 08:58:26',
                'updated_at' => '2024-05-20 08:58:26',
            ),
            57 =>
            array (
                'id' => 58,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 60,
                'email' => 'notaria60_cano@yahoo.com.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 08:58:48',
                'updated_at' => '2024-05-20 08:58:48',
            ),
            58 =>
            array (
                'id' => 59,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 61,
                'email' => 'notaria61_araiza@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 08:59:04',
                'updated_at' => '2024-05-20 08:59:04',
            ),
            59 =>
            array (
                'id' => 60,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 62,
                'email' => 'notaria62mich@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:00:04',
                'updated_at' => '2024-05-20 09:00:04',
            ),
            60 =>
            array (
                'id' => 61,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 63,
                'email' => 'notariapublica63lzc@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:02:50',
                'updated_at' => '2024-05-20 09:02:50',
            ),
            61 =>
            array (
                'id' => 62,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 64,
                'email' => 'notario64morelia@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:03:03',
                'updated_at' => '2024-05-20 09:03:03',
            ),
            62 =>
            array (
                'id' => 63,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 65,
                'email' => 'lic.alecuevas65@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:03:21',
                'updated_at' => '2024-05-20 09:03:21',
            ),
            63 =>
            array (
                'id' => 64,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 66,
                'email' => 'TRASLADOSNOTARIA66@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:03:38',
                'updated_at' => '2024-05-20 09:03:38',
            ),
            64 =>
            array (
                'id' => 65,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 67,
                'email' => 'ibarrera@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:03:55',
                'updated_at' => '2024-05-20 09:03:55',
            ),
            65 =>
            array (
                'id' => 66,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 68,
                'email' => 'salvador-guti12@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:04:11',
                'updated_at' => '2024-05-20 09:04:11',
            ),
            66 =>
            array (
                'id' => 67,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 69,
                'email' => 'notaria_69_zinapecuaro@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:04:28',
                'updated_at' => '2024-05-20 09:04:28',
            ),
            67 =>
            array (
                'id' => 68,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 70,
                'email' => 'notariapub70@msn.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:04:43',
                'updated_at' => '2024-05-20 09:04:43',
            ),
            68 =>
            array (
                'id' => 69,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 71,
                'email' => 'notaria71.mich@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:07:09',
                'updated_at' => '2024-05-20 09:07:09',
            ),
            69 =>
            array (
                'id' => 70,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 72,
                'email' => 'notaria72coalcoman@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:07:23',
                'updated_at' => '2024-05-20 09:07:23',
            ),
            70 =>
            array (
                'id' => 71,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 73,
                'email' => '73notariamich@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:07:44',
                'updated_at' => '2024-05-20 09:07:44',
            ),
            71 =>
            array (
                'id' => 72,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 74,
                'email' => 'notaria74zit@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:08:10',
                'updated_at' => '2024-05-20 09:08:10',
            ),
            72 =>
            array (
                'id' => 73,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 75,
                'email' => 'notaria75@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:08:26',
                'updated_at' => '2024-05-20 09:08:26',
            ),
            73 =>
            array (
                'id' => 74,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 76,
                'email' => 'tdnotaria76@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => '2024-05-20 09:08:38',
                'updated_at' => '2024-05-20 09:09:36',
            ),
            74 =>
            array (
                'id' => 75,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 77,
                'email' => 'notariapublica77quiroga@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:09:56',
                'updated_at' => '2024-05-20 09:09:56',
            ),
            75 =>
            array (
                'id' => 76,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 78,
                'email' => 'notariapublica78michoacan@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:10:15',
                'updated_at' => '2024-05-20 09:10:15',
            ),
            76 =>
            array (
                'id' => 77,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 79,
                'email' => 'notariapub79@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:10:29',
                'updated_at' => '2024-05-20 09:10:29',
            ),
            77 =>
            array (
                'id' => 78,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 80,
                'email' => 'notariapublica80sahuayo@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:10:53',
                'updated_at' => '2024-05-20 09:10:53',
            ),
            78 =>
            array (
                'id' => 79,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 81,
                'email' => 'notariapublica81@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:11:22',
                'updated_at' => '2024-05-20 09:11:22',
            ),
            79 =>
            array (
                'id' => 80,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 82,
                'email' => 'notariapublica_82@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:11:38',
                'updated_at' => '2024-05-20 09:11:38',
            ),
            80 =>
            array (
                'id' => 81,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 83,
                'email' => 'notariap83@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:12:02',
                'updated_at' => '2024-05-20 09:12:02',
            ),
            81 =>
            array (
                'id' => 82,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 84,
                'email' => 'notariapublica84@live.com.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:12:17',
                'updated_at' => '2024-05-20 09:12:17',
            ),
            82 =>
            array (
                'id' => 83,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 85,
                'email' => 'notaria.85@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:12:35',
                'updated_at' => '2024-05-20 09:12:35',
            ),
            83 =>
            array (
                'id' => 84,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 86,
                'email' => 'contabilidadnotaria86@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:12:52',
                'updated_at' => '2024-05-20 09:12:52',
            ),
            84 =>
            array (
                'id' => 85,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 87,
                'email' => 'gabarc2030@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:13:10',
                'updated_at' => '2024-05-20 09:13:10',
            ),
            85 =>
            array (
                'id' => 86,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 89,
                'email' => 'notaria.89@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:13:28',
                'updated_at' => '2024-05-20 09:13:28',
            ),
            86 =>
            array (
                'id' => 87,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 90,
                'email' => 'notaria90patz@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:13:43',
                'updated_at' => '2024-05-20 09:13:43',
            ),
            87 =>
            array (
                'id' => 88,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 91,
                'email' => 'claudianotaria91@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:14:04',
                'updated_at' => '2024-05-20 09:14:04',
            ),
            88 =>
            array (
                'id' => 89,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 92,
                'email' => 'notaria92.traslados@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:14:23',
                'updated_at' => '2024-05-20 09:14:23',
            ),
            89 =>
            array (
                'id' => 90,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 93,
                'email' => 'revisiontrasladosnot93@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:14:48',
                'updated_at' => '2024-05-20 09:14:48',
            ),
            90 =>
            array (
                'id' => 91,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 94,
                'email' => 'notaria94traslados@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:15:19',
                'updated_at' => '2024-05-20 09:15:19',
            ),
            91 =>
            array (
                'id' => 92,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 95,
                'email' => 'catastro@notaria95mich.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:15:40',
                'updated_at' => '2024-05-20 09:15:40',
            ),
            92 =>
            array (
                'id' => 93,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 96,
                'email' => 'erlnotario96zamoramich@outlook.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:16:02',
                'updated_at' => '2024-05-20 09:16:02',
            ),
            93 =>
            array (
                'id' => 94,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 97,
                'email' => 'notaria97@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:16:17',
                'updated_at' => '2024-05-20 09:16:17',
            ),
            94 =>
            array (
                'id' => 95,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 98,
                'email' => 'micklys@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:16:34',
                'updated_at' => '2024-05-20 09:16:34',
            ),
            95 =>
            array (
                'id' => 96,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 99,
                'email' => 'trasladosnot99mich@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:16:50',
                'updated_at' => '2024-05-20 09:16:50',
            ),
            96 =>
            array (
                'id' => 97,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 100,
                'email' => 'sazuan@yahoo.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:17:08',
                'updated_at' => '2024-05-20 09:17:08',
            ),
            97 =>
            array (
                'id' => 98,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 101,
                'email' => 'not101@prodigy.net.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:17:24',
                'updated_at' => '2024-05-20 09:17:24',
            ),
            98 =>
            array (
                'id' => 99,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 102,
                'email' => 'notariapublica102morelia@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:18:07',
                'updated_at' => '2024-05-20 09:18:07',
            ),
            99 =>
            array (
                'id' => 100,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 103,
                'email' => 'solo8a@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:18:22',
                'updated_at' => '2024-05-20 09:18:22',
            ),
            100 =>
            array (
                'id' => 101,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 105,
                'email' => 'notaria105@yahoo.com.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:18:57',
                'updated_at' => '2024-05-20 09:18:57',
            ),
            101 =>
            array (
                'id' => 102,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 106,
                'email' => 'traslados-not106@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:19:15',
                'updated_at' => '2024-05-20 09:19:15',
            ),
            102 =>
            array (
                'id' => 103,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 107,
                'email' => 'not.grim@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:19:36',
                'updated_at' => '2024-05-20 09:19:36',
            ),
            103 =>
            array (
                'id' => 104,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 108,
                'email' => 'notariapublica_108@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:19:56',
                'updated_at' => '2024-05-20 09:19:56',
            ),
            104 =>
            array (
                'id' => 105,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 109,
                'email' => 'notaria_109@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:20:11',
                'updated_at' => '2024-05-20 09:20:11',
            ),
            105 =>
            array (
                'id' => 106,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 110,
                'email' => 'notaria110_2@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:20:34',
                'updated_at' => '2024-05-20 09:20:34',
            ),
            106 =>
            array (
                'id' => 107,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 111,
                'email' => 'kdrv241@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:20:47',
                'updated_at' => '2024-05-20 09:20:47',
            ),
            107 =>
            array (
                'id' => 108,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 112,
                'email' => 'rca@notaria112mich.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:21:02',
                'updated_at' => '2024-05-20 09:21:02',
            ),
            108 =>
            array (
                'id' => 109,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 113,
                'email' => 'notaria113@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:21:20',
                'updated_at' => '2024-05-20 09:21:20',
            ),
            109 =>
            array (
                'id' => 110,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 114,
                'email' => 'notaria_114@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:21:34',
                'updated_at' => '2024-05-20 09:21:34',
            ),
            110 =>
            array (
                'id' => 111,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 115,
                'email' => 'jmmnot-115@outlook.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:22:13',
                'updated_at' => '2024-05-20 09:22:13',
            ),
            111 =>
            array (
                'id' => 112,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 116,
                'email' => 'notpub116@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:22:34',
                'updated_at' => '2024-05-20 09:22:34',
            ),
            112 =>
            array (
                'id' => 113,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 117,
                'email' => 'javiernotario117@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:22:50',
                'updated_at' => '2024-05-20 09:22:50',
            ),
            113 =>
            array (
                'id' => 114,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 118,
                'email' => 'notaria.118.mich@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:23:07',
                'updated_at' => '2024-05-20 09:23:07',
            ),
            114 =>
            array (
                'id' => 115,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 119,
                'email' => 'notaria-119@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:23:20',
                'updated_at' => '2024-05-20 09:23:20',
            ),
            115 =>
            array (
                'id' => 116,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 120,
                'email' => 'tramitesnotaria120@yahoo.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:23:38',
                'updated_at' => '2024-05-20 09:23:38',
            ),
            116 =>
            array (
                'id' => 117,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 122,
                'email' => 'notaria_122@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:24:23',
                'updated_at' => '2024-05-20 09:24:23',
            ),
            117 =>
            array (
                'id' => 118,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 123,
                'email' => 'lcge@prodigy.net.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:24:44',
                'updated_at' => '2024-05-20 09:24:44',
            ),
            118 =>
            array (
                'id' => 119,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 124,
                'email' => 'notaria124mich@prodigy.net.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:25:03',
                'updated_at' => '2024-05-20 09:25:03',
            ),
            119 =>
            array (
                'id' => 120,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 125,
                'email' => 'notaria125jtp@prodigy.net.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:25:20',
                'updated_at' => '2024-05-20 09:25:20',
            ),
            120 =>
            array (
                'id' => 121,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 126,
                'email' => 'notariapublica126@yahoo.com.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:25:35',
                'updated_at' => '2024-05-20 09:25:35',
            ),
            121 =>
            array (
                'id' => 122,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 127,
                'email' => 'notariapublica127@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:25:53',
                'updated_at' => '2024-05-20 09:25:53',
            ),
            122 =>
            array (
                'id' => 123,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 128,
                'email' => 'nota128@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:26:12',
                'updated_at' => '2024-05-20 09:26:12',
            ),
            123 =>
            array (
                'id' => 124,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 130,
                'email' => 'notariapublica130@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:26:36',
                'updated_at' => '2024-05-20 09:26:36',
            ),
            124 =>
            array (
                'id' => 125,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 131,
                'email' => 'notariapublica131@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:26:50',
                'updated_at' => '2024-05-20 09:26:50',
            ),
            125 =>
            array (
                'id' => 126,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 132,
                'email' => 'notaria132@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:27:04',
                'updated_at' => '2024-05-20 09:27:04',
            ),
            126 =>
            array (
                'id' => 127,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 133,
                'email' => 'notaria133@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:27:20',
                'updated_at' => '2024-05-20 09:27:20',
            ),
            127 =>
            array (
                'id' => 128,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 134,
                'email' => 'orihuelacarmona134@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:27:34',
                'updated_at' => '2024-05-20 09:27:34',
            ),
            128 =>
            array (
                'id' => 129,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 135,
                'email' => 'modestobarragan@prodigy.net.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:27:58',
                'updated_at' => '2024-05-20 09:27:58',
            ),
            129 =>
            array (
                'id' => 130,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 136,
                'email' => 'horaciovillicana@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:29:39',
                'updated_at' => '2024-05-20 09:29:39',
            ),
            130 =>
            array (
                'id' => 131,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 137,
                'email' => 'notaria_137@yahoo.com.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:30:31',
                'updated_at' => '2024-05-20 09:30:31',
            ),
            131 =>
            array (
                'id' => 132,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 138,
                'email' => 'notaria138@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:30:57',
                'updated_at' => '2024-05-20 09:30:57',
            ),
            132 =>
            array (
                'id' => 133,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 139,
                'email' => 'morales_notaria139@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:31:33',
                'updated_at' => '2024-05-20 09:31:33',
            ),
            133 =>
            array (
                'id' => 134,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 140,
                'email' => 'notaria140traslados@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:31:56',
                'updated_at' => '2024-05-20 09:31:56',
            ),
            134 =>
            array (
                'id' => 135,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 141,
                'email' => 'manzanoa@armandomanzano.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:32:36',
                'updated_at' => '2024-05-20 09:32:36',
            ),
            135 =>
            array (
                'id' => 136,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 142,
                'email' => 'notariapublica142@live.com.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:32:55',
                'updated_at' => '2024-05-20 09:32:55',
            ),
            136 =>
            array (
                'id' => 137,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 145,
                'email' => 'alfonsocvaca@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:35:05',
                'updated_at' => '2024-05-20 09:35:05',
            ),
            137 =>
            array (
                'id' => 138,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 146,
                'email' => 'luzlagunas@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:35:36',
                'updated_at' => '2024-05-20 09:35:36',
            ),
            138 =>
            array (
                'id' => 139,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 147,
                'email' => 'notaria147@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:35:50',
                'updated_at' => '2024-05-20 09:35:50',
            ),
            139 =>
            array (
                'id' => 140,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 148,
                'email' => 'nena_notaria148@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:36:16',
                'updated_at' => '2024-05-20 09:36:16',
            ),
            140 =>
            array (
                'id' => 141,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 149,
                'email' => 'catastro@notaria149zamora.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:36:28',
                'updated_at' => '2024-05-20 09:36:28',
            ),
            141 =>
            array (
                'id' => 142,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 150,
                'email' => 'notaria150@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:36:47',
                'updated_at' => '2024-05-20 09:36:47',
            ),
            142 =>
            array (
                'id' => 143,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 151,
                'email' => 'herjus03@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:40:09',
                'updated_at' => '2024-05-20 09:40:09',
            ),
            143 =>
            array (
                'id' => 144,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 152,
                'email' => 'ecgn152@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:40:24',
                'updated_at' => '2024-05-20 09:40:24',
            ),
            144 =>
            array (
                'id' => 145,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 153,
                'email' => 'notaria153mich@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:40:43',
                'updated_at' => '2024-05-20 09:40:43',
            ),
            145 =>
            array (
                'id' => 146,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 154,
                'email' => 'notaria154traslados@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:41:01',
                'updated_at' => '2024-05-20 09:41:01',
            ),
            146 =>
            array (
                'id' => 147,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 155,
                'email' => 'notariapublica155_2@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:41:17',
                'updated_at' => '2024-05-20 09:41:17',
            ),
            147 =>
            array (
                'id' => 148,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 156,
                'email' => 'notaria.156@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:41:36',
                'updated_at' => '2024-05-20 09:41:36',
            ),
            148 =>
            array (
                'id' => 149,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 157,
                'email' => 'traslados.not157@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:41:50',
                'updated_at' => '2024-05-20 09:41:50',
            ),
            149 =>
            array (
                'id' => 150,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 158,
                'email' => 'tramite@notaria158.mx',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:42:10',
                'updated_at' => '2024-05-20 09:42:10',
            ),
            150 =>
            array (
                'id' => 151,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 159,
                'email' => 'notario159_cjacosta@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:42:25',
                'updated_at' => '2024-05-20 09:42:25',
            ),
            151 =>
            array (
                'id' => 152,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 160,
                'email' => 'notaria_publica_160@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:44:42',
                'updated_at' => '2024-05-20 09:44:42',
            ),
            152 =>
            array (
                'id' => 153,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 161,
                'email' => 'notaria161mich@yahoo.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:55:08',
                'updated_at' => '2024-05-20 09:55:08',
            ),
            153 =>
            array (
                'id' => 154,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 162,
                'email' => 'gerardoluvianonotario162@yahoo.es',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:55:30',
                'updated_at' => '2024-05-20 09:55:30',
            ),
            154 =>
            array (
                'id' => 155,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 163,
                'email' => 'notaria163traslados@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:55:48',
                'updated_at' => '2024-05-20 09:55:48',
            ),
            155 =>
            array (
                'id' => 156,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 164,
                'email' => 'np164@LIVE.COM.MX',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:56:04',
                'updated_at' => '2024-05-20 09:56:04',
            ),
            156 =>
            array (
                'id' => 157,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 165,
                'email' => 'notaria165arellano@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:56:19',
                'updated_at' => '2024-05-20 09:56:19',
            ),
            157 =>
            array (
                'id' => 158,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 166,
                'email' => 'notariapublica166@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:56:36',
                'updated_at' => '2024-05-20 09:56:36',
            ),
            158 =>
            array (
                'id' => 159,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 167,
                'email' => 'notariapublica167.mich@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:56:52',
                'updated_at' => '2024-05-20 09:56:52',
            ),
            159 =>
            array (
                'id' => 160,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 168,
                'email' => 'notaria_publica_168@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:57:09',
                'updated_at' => '2024-05-20 09:57:09',
            ),
            160 =>
            array (
                'id' => 161,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 169,
                'email' => 'notariapublica169@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:57:23',
                'updated_at' => '2024-05-20 09:57:23',
            ),
            161 =>
            array (
                'id' => 162,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 170,
                'email' => 'rentas@notaria170.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:57:36',
                'updated_at' => '2024-05-20 09:57:36',
            ),
            162 =>
            array (
                'id' => 163,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 172,
                'email' => 'notaria172michoacan@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:57:55',
                'updated_at' => '2024-05-20 09:57:55',
            ),
            163 =>
            array (
                'id' => 164,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 173,
                'email' => 'npub173traslados@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:58:25',
                'updated_at' => '2024-05-20 09:58:25',
            ),
            164 =>
            array (
                'id' => 165,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 174,
                'email' => 'trasladosnotaria174@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:58:42',
                'updated_at' => '2024-05-20 09:58:42',
            ),
            165 =>
            array (
                'id' => 166,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 175,
                'email' => 'notaria175@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:58:59',
                'updated_at' => '2024-05-20 09:58:59',
            ),
            166 =>
            array (
                'id' => 167,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 176,
                'email' => 'notariacharo176@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:59:17',
                'updated_at' => '2024-05-20 09:59:17',
            ),
            167 =>
            array (
                'id' => 168,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 177,
                'email' => 'infonota177@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:59:32',
                'updated_at' => '2024-05-20 09:59:32',
            ),
            168 =>
            array (
                'id' => 169,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 178,
                'email' => 'notaria178michoacan@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 09:59:45',
                'updated_at' => '2024-05-20 09:59:45',
            ),
            169 =>
            array (
                'id' => 170,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 179,
                'email' => 'notaria179michoacan@outlook.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 10:00:03',
                'updated_at' => '2024-05-20 10:00:03',
            ),
            170 =>
            array (
                'id' => 171,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 180,
                'email' => 'notariapublica180@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 10:00:20',
                'updated_at' => '2024-05-20 10:00:20',
            ),
            171 =>
            array (
                'id' => 172,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 181,
                'email' => 'notaria181.catastro@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 10:00:36',
                'updated_at' => '2024-05-20 10:00:36',
            ),
            172 =>
            array (
                'id' => 173,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 182,
                'email' => 'notaria182tarimbaro@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 10:00:54',
                'updated_at' => '2024-05-20 10:00:54',
            ),
            173 =>
            array (
                'id' => 174,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 183,
                'email' => 'notaria183aal@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 10:01:16',
                'updated_at' => '2024-05-20 10:01:16',
            ),
            174 =>
            array (
                'id' => 175,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 184,
                'email' => 'notariavc184@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 10:01:28',
                'updated_at' => '2024-05-20 10:01:28',
            ),
            175 =>
            array (
                'id' => 176,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 185,
                'email' => 'notariapublica185@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 10:01:45',
                'updated_at' => '2024-05-20 10:01:45',
            ),
            176 =>
            array (
                'id' => 177,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 186,
                'email' => 'notaria186@outlook.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 10:02:05',
                'updated_at' => '2024-05-20 10:02:05',
            ),
            177 =>
            array (
                'id' => 178,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 187,
                'email' => 'notaria187uruapan@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 10:02:28',
                'updated_at' => '2024-05-20 10:02:28',
            ),
            178 =>
            array (
                'id' => 179,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 188,
                'email' => 'notario188@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 10:02:54',
                'updated_at' => '2024-05-20 10:02:54',
            ),
            179 =>
            array (
                'id' => 180,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 189,
                'email' => 'notaria189mich@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 10:03:09',
                'updated_at' => '2024-05-20 10:03:09',
            ),
            180 =>
            array (
                'id' => 181,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 190,
                'email' => 'contabilidad.notaria190@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 10:03:25',
                'updated_at' => '2024-05-20 10:03:25',
            ),
            181 =>
            array (
                'id' => 182,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 191,
                'email' => 'notariamich191@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 10:03:42',
                'updated_at' => '2024-05-20 10:03:42',
            ),
            182 =>
            array (
                'id' => 183,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 192,
                'email' => 'notaria192morelia@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 10:04:04',
                'updated_at' => '2024-05-20 10:04:04',
            ),
            183 =>
            array (
                'id' => 184,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 193,
                'email' => 'notariapublica193michoacan@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 10:04:38',
                'updated_at' => '2024-05-20 10:04:38',
            ),
            184 =>
            array (
                'id' => 185,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 195,
                'email' => 'notaria195mich@hotmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 10:05:10',
                'updated_at' => '2024-05-20 10:05:10',
            ),
            185 =>
            array (
                'id' => 186,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 199,
                'email' => 'notaria199p@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 10:05:59',
                'updated_at' => '2024-05-20 10:05:59',
            ),
            186 =>
            array (
                'id' => 187,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 200,
                'email' => 'notario200mich@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => NULL,
                'created_at' => '2024-05-20 10:06:19',
                'updated_at' => '2024-05-20 10:06:19',
            ),
            187 =>
            array (
                'id' => 188,
                'estado' => 'activo',
                'dependencia' => NULL,
                'numero_notaria' => 203,
                'email' => 'notariapublicamich203@gmail.com',
                'notario' =>null,
                'adscrito' => NULL,
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => '2024-05-20 10:07:35',
                'updated_at' => '2024-05-21 10:37:20',
            ),
        ));

        Schema::enableForeignKeyConstraints();

    }
}
