<?php

namespace App\Constantes;

class Constantes{

    const AREAS = [
        'Roles',
        'Permisos',
        'Usuarios',
        'Auditoría',
        'Entidades',
        'Catastro',
        'RPP',
        'Administración',
        'Consultas'
    ];

    const TIPO_VIALIDADES = [
        'AMPLIACIÓN',
        'ANDADOR',
        'ARROYO O CANAL',
        'AVENIDA',
        'BOULEVARD',
        'BRECHA',
        'CALLE',
        'CALLEJÓN',
        'CALZADA',
        'CAMINO',
        'CAMINO REAL',
        'CARRETERA',
        'CERRADA',
        'CIRCUITO',
        'CIRCUNVALACIÓN',
        'CONTINUACIÓN',
        'CORREDOR',
        'CUARTEL',
        'DIAGONAL',
        'EJE VIAL',
        'PASAJE',
        'PEATONAL',
        'PERIFÉRICO',
        'PLAZA',
        'PORTAL',
        'PRIVADA',
        'PROLONGACIÓN',
        'RETORNO',
        'SERVIDUMBRE DE PASO',
        'VIADUCTO'
    ];

    const TIPO_ASENTAMIENTO = [
        'AEROPUERTO',
        'AMPLIACIÓN',
        'BARRIO',
        'CANTON',
        'CIUDAD',
        'CIUDAD INSDUSTRIAL',
        'COLONIA',
        'CONDOMINIO',
        'CONJUNTO HABITACIONAL',
        'CORREDOR INDUSTRIAL',
        'COTO',
        'CUARTEL',
        'EJIDO',
        'EX-EJIDO',
        'EXHACIENDA',
        'FRACCIÓN',
        'FRACCIONAMIENTO',
        'GRANJA',
        'HACIENDA',
        'INGENIO',
        'MANZANA',
        'PARAJE',
        'PARQUE INDUSTRIAL',
        'POBLADO',
        'PRIVADA',
        'PROLONGACIÓN',
        'PUEBLO',
        'PUERTO',
        'RANCHERIA',
        'RANCHO',
        'REGIÓN',
        'RESIDENCIAL',
        'RINCONADA',
        'SECCIÓN',
        'SECTOR',
        'SUPERMANZANA',
        'TENENCIA',
        'UNIDAD',
        'UNIDAD HABITACIONAL',
        'VILLA',
        'ZONA FEDERAL',
        'ZONA INDUSTRIAL',
        'ZONA MILITAR',
        'ZONA NAVAL',
    ];

    const VIENTOS = [
        'ANEXO',
        'ESTE',
        'NORESTE',
        'NOROESTE',
        'NORORIENTE',
        'NORPONIENTE',
        'NORTE',
        'OESTE',
        'ORIENTE',
        'PONIENTE',
        'SUR',
        'SURESTE',
        'SUROESTE',
        'SURORIENTE',
        'SURPONIENTE',
    ];

    const AÑOS = [
        '2023',
        '2024',
        '2025'
    ];
    const DOCUMENTO_ENTRADA = [
        'ESCRITURACIÓN SOCIAL',
        'ESCRITURA PÚBLICA',
        'ESCRITURA PRIVADA',
        'TÍTULO DE PROPIEDAD PARCELARIO',
        'TÍTULO DE PROPIEDAD SOLAR URBANO',
        'CONTRATO DE COMPRAVENTA',
        'MINUTA DE PROPIEDAD COMUNIDAD INDIGENA'
    ];

    const ESTADOS = [
        'Aguascalientes',
        'Baja California',
        'Baja California Sur',
        'Campeche',
        'Chiapas',
        'Chihuahua',
        'Ciudad de México',
        'Coahuila',
        'Colima',
        'Durango',
        'Estado de México',
        'Guanajuato',
        'Guerrero',
        'Hidalgo',
        'Jalisco',
        'Michoacán',
        'Morelos',
        'Nayarit',
        'Nuevo León',
        'Oaxaca',
        'Puebla',
        'Querétaro',
        'Quintana Roo',
        'San Luis Potosí',
        'Sinaloa',
        'Sonora',
        'Tabasco',
        'Tamaulipas',
        'Tlaxcala',
        'Veracruz',
        'Yucatán',
        'Zacatecas',
    ];

    const ESTADO_CIVIL = [
        'CASADO',
        'SOLTERO',
        'VIUDO',
        'DIVORCIADO'
    ];

    const ACTOS = [
        'ACTUALIZACION',
        'ADJUDICACION DE BIEN INMUEBLE',
        'ADJUDICACION EXTINCION PARCIAL DE PROP',
        'ADJUDICACION POR HERENCIA',
        'ADJUDICACIÓN POR REMATE',
        'ADJUDICACION POR SUCESION TESTAMENTARIA',
        'ADJUDICACION SUCESION INTESTAMENTARIA',
        'AVISO ACLARATORIO',
        'CAMBIO DE LOCALIDAD',
        'CAMBIO DE REGIMEN',
        'CANCELACION DE ESCRITURA O TRASLADO',
        'CANCELACIÓN DE RESERVA DE DOMINIO',
        'CANCELACIÓN DE SUBDIVISIÓN',
        'CANCELACIÓN DE TÍTULO DE PROPIEDAD',
        'CANCELACION POR DUPLICIDAD',
        'CESION DE DERECHOS',
        'CESION DE DERECHOS HEREDITARIOS',
        'CESION ONEROSA DERECHOS HEREDITARIOS',
        'COMPRA PARCIAL',
        'COMPRA VENTA',
        'COMPRA VENTA ADCORPUS RESERVA DE DOMINIO',
        'COMPRA VENTA DE USUFRUTO VITALICIO',
        'COMPRA VENTA TOTAL',
        'COMPRA VENTA TOTAL CON RESERVA DOMINIO',
        'COMPRAVENTA AD-CORPUS',
        'COMPRA-VENTA DE ACCIONES Y DERECHOS',
        'COMPRA-VENTA DE LA NUDA PROPIEDAD',
        'COMPRA-VENTA DERECHOS DE COOPROPIEDAD',
        'CONSTITUCION DE REGIMEN EN CONDOMINIO',
        'DISOLUCION DE COPROPIEDAD',
        'DIVISION DE COSA COMUN',
        'DIVISIÓN Y PARTICIÓN DE COSA COMÚN',
        'DIVISION Y PARTICION PARCIAL DE C COMÚN',
        'DONACION A TITULO GRATUITO',
        'DONACIÓN CON RESERVA DE USUFRUCTO VITALICIO',
        'DONACION DE ACCIONES Y DERECHOS',
        'DONACIÓN DE DERECHOS DE COPROPIEDAD',
        'DONACION DE INMUEBLE',
        'DONACION DE LA NUDA PROPIEDAD',
        'DONACION DE USUFRUCTO',
        'DONACIÓN ONEROSA',
        'DONACIÓN PURA Y SIMPLE',
        'EJECUCIÓN PARCIAL DE FIDEICOMISO',
        'EXTINCION DE FIDEICOMISO',
        'EXTINCIÓN DE USUFRUCTO VITALICIO',
        'EXTINCIÓN DEL REGIMEN DE PROP. EN COND.',
        'EXTINCIÓN PARCIAL DE FIDEICOMISO',
        'FIDEICOMISO',
        'FUSION DE PREDIO',
        'FUSION DE SOCIEDADES',
        'FUSIONES',
        'JUICIO SUCESORIO INTESTAMENTARIO',
        'JUICIO SUCESORIO TESTAMENTARIO',
        'JUICIO SUMARIO CIVIL HIPOTECARIO',
        'LIQUIDACIÓN DE SOCIEDAD CONYUGAL',
        'NULIDAD ABSOLUTA DE LA ESCRITURA',
        'NULIDAD ABSOLUTA SUCESORIO INTESTAMENTAR',
        'NULIDAD DE DILIGENCIAS AD. PERPETUAM',
        'NULIDAD DE EXPROPIACIÓN',
        'NULIDAD DE RECT. DE SUPERFICIE',
        'PERMUTA ACCIONES Y DERECHOS DE INMUEBLE',
        'PERMUTA CON DONACIÓN',
        'PRESCRIPCIÓN POSITIVA Y ADQUISITIVA',
        'PROTOCOLIZACION DE CONTRATO DE USUFRUCTO',
        'PROTOCOLIZACIÓN DE CONTRATO PRIVADO DE DONACIÓN',
        'PROTOCOLIZACIÓN JUICIO SUCESORIO INTESTAMENTARIO',
        'PROTOCOLIZACIÓN JUICIO SUCESORIO TESTAMENTARIO',
        'REVERSIÓN DE FIDEICOMISO',
        'REVERSION PARCIAL EN EJECUCION DE FIDEIC',
        'REVISIÓN INMUEBLE EJECUCIÓN FIDEICOMISO',
        'SUCESIÓN EXTRAJUDICIAL INTESTAMENTARIA',
        'SUCESIÓN EXTRAJUDICIAL TESTAMENTARIA',
        'TRAMITACIÓN EXTRAJUDICIAL',
        'TRANSMICION DE ACCIONES Y DERECHOS',
        'TRANSMISION DE NUDA PROP. Y/O  USUFRUCTO',
        'VARIACION CATASTRAL',
        'VENTA DE ACCIONES Y DERECHOS',
        'VENTA PARCIAL',
    ];

    const TIPO_ESCRITURA = [
        'ESCRITURA PUBLICA',
        'ESCRITURA PRIVADA',
        'TITULO DE PROPIEDAD',
        'CONTRATO DE COMPRAVENTA',
        'MINUTA DE PROPIEDAD COMUNIDAD INDIGENA'
    ];

    const DISTRITOS = [
        1 => '01 Morelia',
        2 => '02 Uruapan',
        3 => '03 Zamora',
        4 => '04 Apatzingán',
        5 => '05 Hidalgo',
        6 => '06 Tacámbaro',
        7 => '07 Pátzcuaro',
        8 => '08 Zitácuaro',
        9 => '09 Jiquilpan',
        10 => '10 Zinapécuaro',
        11 => '11 Zacapu',
        12 => '12 La Piedad',
        13 => '13 Huetamo',
        14 => '14 Maravatío',
        15 => '15 Salazar',
        16 => '16 Puruándiro',
        17 => '17 Coalcoman',
        18 => '18 Ario De Rosales',
        19 => '19 Tanhuato'
    ];

    const SECCIONES = [
        'Propiedad',
        'Gravamen',
        'Sentencias',
        'Varios',
        'Cancelaciones',
        'Fraccionamientos',
        'Comercio'
    ];

    const ACTORES_FIDEICOMISO = [
        'FIDUCIARIA',
        'FIDEICOMITENTE',
        'FIDEICOMISARIO',
    ];

    const MUNICIPIOS = [
        1 => 'ACUITZIO',
        2 => 'AGUILILLA',
        3 => 'ALVARO OBREGON',
        4 => 'ANGAMACUTIRO',
        5 => 'ANGANGUEO',
        6 => 'APATZINGAN',
        7 => 'APORO',
        8 => 'AQUILA',
        8 => 'LA PLACITA',
        9 => 'ARIO',
        9 => 'URAPA',
        10 => 'ARTEAGA',
        11 => 'BRISEÑAS',
        12 => 'BUENAVISTA',
        12 => 'FELIPE CARRILLO PUERTO',
        13 => 'CARACUARO',
        14 => 'COAHUAYANA',
        15 => 'COALCOMAN',
        16 => 'COENEO',
        17 => 'CONTEPEC',
        18 => 'COPANDARO',
        19 => 'COTIJA',
        20 => 'CUITZEO',
        21 => 'CHARAPAN',
        22 => 'CHARO',
        23 => 'CHAVINDA',
        24 => 'CHERAN',
        25 => 'CHILCHOTA',
        26 => 'CHINICUILA',
        27 => 'CHUCANDIRO',
        28 => 'CHURINTZIO',
        29 => 'CHURUMUCO',
        30 => 'ECUANDUREO',
        31 => 'EPITACIO HUERTA',
        32 => 'ERONGARICUARO',
        33 => 'GABRIEL ZAMORA',
        34 => 'HIDALGO',
        34 => 'ANTONIO VILLALONGIN',
        34 => 'EL CARACOL',
        34 => 'AGOSTITLAN',
        34 => 'TENENCIA CIUDAD HIDALGO',
        35 => 'LA HUACANA',
        35 => 'ZICUIRAN',
        36 => 'HUANDACAREO',
        37 => 'HUANIQUEO',
        38 => 'HUETAMO',
        39 => 'HUIRAMBA',
        40 => 'INDAPARAPEO',
        41 => 'IRIMBO',
        42 => 'IXTLAN',
        43 => 'JACONA',
        44 => 'JIMENEZ',
        45 => 'JIQUILPAN',
        46 => 'JUAREZ',
        47 => 'JUNGAPEO',
        48 => 'LAGUNILLAS',
        49 => 'MADERO',
        49 => 'D CURUCUPASEO',
        50 => 'MARAVATIO',
        51 => 'MARCOS CASTELLANOS',
        52 => 'LAZARO CARDENAS',
        52 => 'LA MIRA',
        52 => 'GUACAMAYAS',
        53 => 'MORELIA',
        53 => 'SANTIAGO UNDAMEO',
        53 => 'CHIQUIMITIO',
        53 => 'TIRIPETIO',
        53 => 'CAPULA',
        53 => 'TEREMENDO',
        53 => 'TENENCIA MORELIA',
        54 => 'MORELOS',
        55 => 'MUGICA',
        56 => 'NAHUATZEN',
        57 => 'NOCUPETARO',
        58 => 'NUEVO PARANGARICUTIRO',
        59 => 'NUEVO URECHO',
        60 => 'NUMARAN',
        61 => 'OCAMPO',
        62 => 'PAJACUARAN',
        63 => 'PANINDICUARO',
        64 => 'PARACUARO',
        65 => 'PARACHO',
        66 => 'PATZCUARO',
        66 => 'CUANAJO',
        66 => 'SAN JUAN TUMBIO',
        67 => 'PENJAMILLO',
        67 => 'SANTA FE DEL RIO',
        67 => 'ZIQUITARO',
        68 => 'SAN FRANCISCO PERIBAN',
        68 => 'PERIBAN',
        69 => 'LA PIEDAD',
        70 => 'PUREPERO',
        71 => 'PURUANDIRO',
        71 => 'JANAMUATO',
        71 => 'GALEANA',
        71 => 'TENENCIA DE PURUANDIRO',
        71 => 'LA QUEMADA',
        72 => 'QUERENDARO',
        73 => 'QUIROGA',
        74 => 'COJUMATLAN DE REGULES',
        75 => 'LOS REYES',
        75 => 'PAMATACUARO',
        75 => 'TENENCIA LOS REYES',
        75 => 'ZACAN',
        76 => 'SAHUAYO',
        77 => 'SAN LUCAS',
        78 => 'SANTA ANA MAYA',
        79 => 'SALVADOR ESCALANTE',
        79 => 'ZIRAHUEN',
        79 => 'OPOPEO',
        80 => 'SENGUIO',
        81 => 'SUSUPUATO',
        82 => 'TACAMBARO',
        82 => 'TECARIO',
        83 => 'TANCITARO',
        83 => 'APO',
        83 => 'PAREO',
        84 => 'SANTIAGO TANGAMANDAPIO',
        84 => 'TARECUATO',
        85 => 'TANGANCICUARO',
        85 => 'PATAMBAN',
        86 => 'TANHUATO',
        87 => 'TARETAN',
        88 => 'TARIMBARO',
        88 => 'TEJARO',
        89 => 'TEPALCATEPEC',
        90 => 'TINGAMBATO',
        90 => 'PICHATARO',
        91 => 'TINGUINDIN',
        91 => 'TACATZCUARO',
        91 => 'AQUILES SERDAN',
        92 => 'TIQUICHEO DE N R',
        93 => 'TLALPUJAHUA',
        94 => 'TLAZAZALCA',
        95 => 'TOCUMBO',
        96 => 'TUMBISCATIO',
        97 => 'TURICATO',
        97 => 'PURUARAN',
        98 => 'TUXPAN',
        99 => 'TUZANTLA',
        100 => 'TZINTZUNTZAN',
        101 => 'TZITZIO',
        102 => 'URUAPAN',
        103 => 'VENUSTIANO CARRANZA',
        103 => 'LA PALMA',
        104 => 'VILLAMAR',
        104 => 'JARIPO',
        105 => 'VISTA HERMOSA',
        106 => 'YURECUARO',
        107 => 'ZACAPU',
        107 => 'TENENCIA ZACAPU',
        108 => 'ZAMORA',
        108 => 'ARIO DE RAYON',
        108 => 'ATACHEO',
        108 => 'ATECUCARIO',
        108 => 'LA SAUCEDAD',
        109 => 'ZINAPARO',
        110 => 'ZINAPECUARO',
        110 => 'UCAREO',
        110 => 'V DE JUAREZ',
        111 => 'ZIRACUARETIRO',
        111 => 'SAN A ZURUMUCAPIO',
        112 => 'ZITACUARO',
        112 => 'CRESCENCIO MORALES',
        113 => 'JOSE SIXTO VERDUZCO',
        150 => 'OFNAS. DEL DISTRITO',
    ];

}
